### ISSUE TITLE
using native-tls feature results in build error

### ISSUE THREAD

**Issue by pgokul** [algesten/ureq#278] opened 2020-12-13 17:04 UTC
I am trying to use the native-tls feature with ureq. Here is a snippet of my Cargo file

```
native-tls = "0.2.6"
ureq = { version = "*", features = ["json", "charset","native-tls"] }
```

when i issue a cargo build, i get the following errors

```
Compiling ureq v1.5.4
error[E0425]: cannot find function `connect_https` in module `stream`
   --> /Users/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/ureq-1.5.4/src/unit.rs:311:28
    |
311 |         "https" => stream::connect_https(&unit, hostname),
    |                            ^^^^^^^^^^^^^ help: a function with a similar name exists: `connect_http`
    | 
   ::: /Users/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/ureq-1.5.4/src/stream.rs:314:1
    |
314 | pub(crate) fn connect_http(unit: &Unit, hostname: &str) -> Result<Stream, Error> {
    | -------------------------------------------------------------------------------- similarly named function `connect_http` defined here

error[E0599]: no variant or associated item named `Https` found for enum `stream::Stream` in the current scope
   --> /Users/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/ureq-1.5.4/src/stream.rs:170:21
    |
27  | pub enum Stream {
    | --------------- variant or associated item `Https` not found here
...
170 |             Stream::Https(b) => Some(&b.get_ref().sock),
    |                     ^^^^^
    |                     |
    |                     variant or associated item not found in `stream::Stream`
    |                     help: there is a variant with a similar name: `Http`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0425, E0599.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `ureq`
```

removing nattive-tls makes the error go away. However i cannot use the method set_tls_connector .

Am i missing any extra dependencies in my cargo file?

**Comment by algesten** [comment] 2020-12-13 17:55
Hi! Thanks for using ureq!

Sorry you're having problems with this feature. I will look into it – might have been a regression on the 1.x branch as our attention is on the 2.0 release.

In 2.0 we decided to remove native-tls since maintaining double TLS libraries made the code very unwieldy (and prone to the kind of error you found).

Since we're just about to release 2.0, I just want to verify our decision of removing native-tls. If you don't mind me asking, is rustls not doing what you need? Why native-tls?

**Comment by pgokul** [comment] 2020-12-14 05:10
I am trying to connect to a server with a self signed certificate. The certificate is added to the native OS certificate store but rustls seems to have problems verifying it. Was trying to see if native-tls uses the OS certificate store.
For now i have disabled certificate verification with rustls using the code  from https://github.com/algesten/ureq/pull/121 but is there any way to force rustls to use the OS certificate store for verification?

Thanks for an incredibly easy to use library.

**Comment by jsha** [comment] 2020-12-14 20:22
> is there any way to force rustls to use the OS certificate store for verification?

It should be possible with rustls-native-certs: https://github.com/ctz/rustls-native-certs. You would add that as a dependency, then set up your own rustls ClientConfig using it, and pass that to ureq. We should probably add step-by-step documentation for this, since I think it's a common use case.

**Comment by pgokul** [comment] 2020-12-15 06:11
Thanks @jsha . I will try it out.

**Comment by algesten** [comment] 2021-01-03 20:14
Closing since 2.0.0 is out now.

**Closed by algesten** 2021-01-03 20:14 UTC
