### ISSUE TITLE
Keep-Alive connections

### ISSUE THREAD

**Issue by whyCPPgofast** [algesten/ureq#199] opened 2020-10-22 11:18 UTC
Hi guys, just wanted to say im very satisfied with the library and the great work you've done. 

I was looking through the code and couldn't find the part where Keep-Alive connections are implemented. 

I was trying to figure out if there is a way to set a default timeout for the Keep-Alive connections like 30/60/90 seconds.

Does such default value even exist?

**Comment by jsha** [comment] 2020-10-22 16:31
Hi! Glad you like to project. Thanks for the kind words.

Connection pooling is handled mostly in pool.rs. Right now there is no way to set how long an idle connection will live. Connections live in the pool until either the server closes them or they are kicked out of the pool because there are too many connections to other hosts.

I'd kind of like to fix that, since it means (I think) we can have a lot of connections sitting around in the OS in CLOSE_WAIT until we try to reuse them, do a non-blocking read, and find they are closed. It's not the worst thing in the world, but it is a bit of a waste of resources.

The problem is, I think the only way to accomplish that would be to have a worker thread that periodically checks each connection in a pool to see if it is still alive. If we had that, we could also implement the feature you're discussing, where the client can proactively close idle connections after a period of time. Currently ureq doesn't spawn any such worker threads, which keeps things nice and simple, but we might eventually conclude that we want to.

Would you mind telling us more about your use case?

**Comment by whyCPPgofast** [comment] 2020-10-24 01:19
My case is this: make periodic requests to the same host every 2 seconds, by using Keep-alive I can avoid the latency of the handshake. In my case idle connections would not really be a thing unless that particular host changes their IP.

**Comment by jsha** [comment] 2020-10-24 01:26
It sounds like the existing Agent will probably meet your needs: https://docs.rs/ureq/1.5.1/ureq/struct.Agent.html

**Comment by whyCPPgofast** [comment] 2020-10-24 02:25
Thanks that will do it, I think you should consider putting that into the main README. You'll have less people asking about features that already exist.

**Comment by jsha** [comment] 2020-10-24 07:17
You're correct; currently the connection will be reused even after an hour, so long as the server hasn't closed it. However, most servers will close idle connections after an hour.

You're also right that we should feature Agent more prominently in the documentation! We have a number of changes coming up for version 2.0; I hope to include that among them.

**Closed by jsha** 2020-10-24 07:17 UTC
