### ISSUE TITLE
Ability to debug internal errors

### ISSUE THREAD

**Issue by xMAC94x** [algesten/ureq#122] opened 2020-07-29 08:16 UTC
Hi @algesten , we are the veloren team (a rust game) and we decided to use your ureq crate a few months ago for our auth api to replace `reqwest`. We love the fact that it's so small and straight to the point.

But we just discoverd an issue. We are getting a 500 syntetic error BadStatus, similar to #10  (but not exactly).
We updated to `1.3` just to be sure, but the error is still persistent.
It seems to come sporadically all 5 minutes and looks like tls related.

I've read your reason for the `Synthetic errors` but in case something is Bad inside `ureq` or maybe in the way we are handling it, it makes stuff super hard to debug.

Do you have a default approach to take on errors like this ? btw we are using default-features = false and use only "tls"

**Comment by jsha** [comment] 2020-07-29 08:45
Thanks for the report! Can you share the relevant snippet of your code and
the detailed error output that goes with the 500 error? Also if you can
make an instance of the server available online that would be useful for
testing.

**Comment by xMAC94x** [comment] 2020-07-30 07:47
Hi @jsha  relevant snippet of code isn't that easy as we only detected it for our full setup. Let me try to explain:
```
Veloren_Gameserver +
+  ^               +----------------->   HTTPS Proxy(Caddy)  +------->  Authentication Server
|  |
|  |                                      ^
v  +                                      |
Veloren_Client  +-------------------------+
```

We have our Gameserver and our Client, that tries to connect to the Gameserver to join a normal multiplayer game.
In the cloud we have a central authentication server behind a HTTPS Reverse proxy.
Both the Veloren_Client and Veloren_Gameserver need to access the Authentication Server for the login procedure. Both are using `ureq` as a client while we use `rouille` as the server.

We noticed that the server can get reproduceable a syntetic error. I spend yesterday to improve our error Reporting so that it's easier to test for you :)
The relevant code (that runs in both Veloren_Client and Veloren_Gameserver) is this: https://gitlab.com/veloren/auth/-/blob/93c5819c502bd912cca6fc2fff9d9817564b1de1/authc/src/lib.rs 
It's doing all the `ureq` code we have.

If you want to reproduce the error for yourself, clone our game repository: https://gitlab.com/veloren/veloren/ and start it with `cargo run`. you have to create yourself an account at https://account.veloren.net/ (just some dummy values, but remember it good, as we don't have a email recovery yet).

In the game now execute the following steps
1. enter `pftclan.de` as server address and enter username and pass
2. click the Multiplayer button.
2a. It works and you come to an character screen: Logout and wait 5 minutes (use a clock to be sure it's 5 mins) and repeat step 2.
2b: You get an error "Auth error on server: Request failed, connection error with text Failed to read status line". Where `Failed to Read Status line` is the `ureq` error. continue!
3. Login again, NOW it will work guranteed. You see the character screen
4. Logout again.
5. Wait 5 minutes(use a clock).
6. Jump to step 2. and repeat. (you will get the same error again, guaranteed).

The fact that we only get the error after 5 mins, leads us to the hint that it might be a timeout killing the HTTPS connection which then leading to a `read status line ` error. But we are no experts here. (the same ureq::Agent is reused from here: https://gitlab.com/veloren/veloren/-/blob/master/server/src/login_provider.rs)
We would be super happy if you can verify the behavior yourself and can confirm that it's some strange bug.
Have a nice day :)

**Comment by algesten** [comment] 2020-07-30 15:50
@xMAC94x Thanks for the very detailed report!

It sounds like we might have a bug in `ureq::Agent` where a pooled connection fails after lying dormant in the Agent for a while.

Just to verify that theory, could you temporarily stop using an Agent and just use `ureq::get`/`ureq::post` etc at each call site to cut out the pooling?

**Comment by Songtronix** [comment] 2020-07-31 05:31
Just confirmed. Without using the `Agent` everything works as expected. Incase it matters we use `Caddy` as SSL Proxy infront of our Authentication. I'm not even sure if we want to use `Agent` as the auth connection will only be used once per login into the gameserver.

**Comment by algesten** [comment] 2020-07-31 10:57
@Songtronix @xMAC94x Thanks for your help in this! I'm going to close this specific issue since I captured what's going on in #124

**Closed by algesten** 2020-07-31 10:57 UTC
