### ISSUE TITLE
Can not implement TlsConnector::connect

### ISSUE THREAD

**Issue by erkbb** [algesten/ureq#461] opened 2021-12-23 14:56 UTC
Hi, 
thanks for adding `native-tls` support.  
I am trying to implement `TlsConnector::connect` to do some additional server certificate verification but get the compiler error `module stream is private`. Am I doing sth wrong here? Is there any other way to access the TlsStream or `TlsStream::peer_certificate`?

```rust
impl TlsConnector for CustomTlsConnector {
    fn connect(&self, dns_name: &str, tcp_stream: TcpStream) -> Result<Box<dyn ureq::stream::HttpsStream>, Error> {
         todo!()
    }
}
```

ureq version 2.4.0 with features `native-tls` and `json` on Rust 1.54.0 (Windows x64)

**Comment by algesten** [comment] 2021-12-23 15:29
Hi @erkbb! Welcome to ureq. Our first issue with 2.4.0. Exciting! :D 

I see what the problem is, we need to export `HttpsStream` (or similar). 

I'll rush out a fix for this.

**Closed** 2022-01-22 09:41 UTC
